terminal=kitty
launcher=rofi -show drun

bar_color=#2968cc
bar_height=20
bar_visible=false

background_wallpaper=wallpaper_directory

autoexec1=pipewire &
autoexec2=pipewire-pulse &
autoexec3=wireplumber &
autoexec4=picom &
autoexec5=echo 'welcome to tywm'
autoexec6=~/.config/polybar/launch.sh

border_width=3
border_color=#2968cc

float_keybind=f
terminal_keybind=Return
kill_keybind=c
focus_next_keybind=k
unfloat_keybind=v
toggle_bar_keybind=b
launcher_keybind=r
reload_keybind=p
